export { IconDelete } from './IconDelete'
export { IconFile } from './IconFile'
export { IconFolder } from './IconFolder'
export { IconRename } from './IconRename'
export { IconOpenFolder } from './IconOpenFolder'
export { IconStar } from './IconStart'